FROM webhippie/alpine:latest-arm64@sha256:bfd0976b1d609a9ae51e26d516f7bf73cc9ab1c708ce519cdc96c7bd8f14300f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
