FROM webhippie/alpine:latest-arm32v6@sha256:d200d1dd150cd8d81d8bff0bd98641884979074ca158481239ed5a2ed95dd031

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Python" \
  org.label-schema.vcs-url="https://github.com/dockhippie/python.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add build-base python3-dev python3 py3-pip && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
