FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:d2ddc16b136cd196ae03fa554616c7ffaf49ec186d22ad68145ce124e6804669

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
