FROM webhippie/alpine:latest-amd64@sha256:0f01e71f5f6079c7cdba767907024e3aa3b20e2ae6c426dfe18a4f497f57af3b

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
