FROM webhippie/alpine:latest-arm64v8@sha256:248d3c19cd10e084aee1ad346ba0b1068d5cdeed5ef3dce5dce3e0ec26a07eb8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Python" \
  org.label-schema.vcs-url="https://github.com/dockhippie/python.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add build-base python3-dev python3 py3-pip && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
