FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:3cf3f74b77dc81964328fffd069d826c8a5d6e32239de40ca203f025784bd110

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
