FROM webhippie/alpine:latest-arm@sha256:ccb76bc8e425029329a7129a9d05304b8f5334a7fca579bfb6055f46b1ff9464

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
