FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:5d2de211416cfc15c49ea242b56a1479269ed58c1c44645370a6fcbd433ab707

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
