FROM webhippie/alpine:latest-amd64@sha256:d4a2e552a508f318faf37edd794c9003270b418a1f44f88998e8a5233b0ba6b7

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
