FROM webhippie/alpine:latest-arm64v8@sha256:a0363510c6b924b106b4b0387fbd93f6823161d99cb7de3ae6fbb937970fc2b5

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Python" \
  org.label-schema.vcs-url="https://github.com/dockhippie/python.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add build-base python3-dev python3 py3-pip && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
