FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:03bbf25770048db3c6c1f2b19a75714094a82696c51bd2418beafa0ce070911c

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add build-base openssl-dev libffi-dev git python3-dev python3 py3-pip py3-tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
