FROM webhippie/alpine:latest-arm32v6@sha256:786f97f21b334404ebd651fd7a0a3669cf89c9b018cd27650a28334290f286bd

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Python" \
  org.label-schema.vcs-url="https://github.com/dockhippie/python.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add build-base python3-dev python3 py3-pip && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
