FROM webhippie/alpine:latest-amd64@sha256:8d58440d5b5dbe614d09786ac33f733982c0787dc99ad5545246ebc2a688e7a4

WORKDIR /srv/app

# renovate: datasource=github-tags depName=python/cpython
ENV PYTHON_VERSION=v2.7.18

RUN apk update && \
  apk upgrade && \
  apk add build-base git expat-dev openssl-dev zlib-dev ncurses-dev bzip2-dev gdbm-dev sqlite-dev libffi-dev readline-dev linux-headers && \
  curl -sLo - https://www.python.org/ftp/python/${PYTHON_VERSION#v}/Python-${PYTHON_VERSION#v}.tgz | tar -xzf - -C /tmp && \
  cd /tmp/Python-${PYTHON_VERSION#v} && \
  ./configure --prefix=/usr --enable-shared --with-threads --enable-ipv6 --with-system-ffi --with-system-expat --with-system-zlib --enable-unicode=ucs4 && \
  make && \
  make install && \
  cd && \
  rm -rf /tmp/Python-${PYTHON_VERSION#v} && \
  curl -sLo - https://bootstrap.pypa.io/pip/2.7/get-pip.py | python && \
  pip install -U pip tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
