FROM webhippie/alpine:latest-amd64@sha256:4306b1ddc97e09a6f985406eb280b95f940f784a9379fd8d6efd563b372ccac8

WORKDIR /srv/app

# renovate: datasource=github-tags depName=python/cpython
ENV PYTHON_VERSION=v3.10.7

RUN apk update && \
  apk upgrade && \
  apk add build-base git expat-dev openssl-dev zlib-dev ncurses-dev bzip2-dev xz-dev sqlite-dev libffi-dev tcl-dev linux-headers gdbm-dev readline-dev && \
  curl -sLo - https://www.python.org/ftp/python/${PYTHON_VERSION#v}/Python-${PYTHON_VERSION#v}.tgz | tar -xzf - -C /tmp && \
  cd /tmp/Python-${PYTHON_VERSION#v} && \
  ./configure --prefix=/usr --disable-rpath --enable-ipv6 --enable-loadable-sqlite-extensions --enable-shared --with-lto --with-computed-gotos --with-dbmliborder=gdbm:ndbm --with-system-expat --with-system-ffi --with-threads && \
  make && \
  make install && \
  ln -sf /usr/bin/python3.10 /usr/bin/python && \
  ln -sf /usr/bin/pip3.10 /usr/bin/pip && \
  ln -sf /usr/bin/python3.10m-config /usr/bin/python-config && \
  ln -sf /usr/bin/pydoc3.10 /usr/bin/pydoc && \
  ln -sf /usr/bin/easy_install-3.10 /usr/bin/easy_install && \
  ln -sf /usr/bin/idle3.10 /usr/bin/idle && \
  cd && \
  rm -rf /tmp/Python-${PYTHON_VERSION#v} && \
  curl -sLo - https://bootstrap.pypa.io/get-pip.py | python && \
  pip install -U pip tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
