FROM webhippie/alpine:latest-arm64@sha256:68db6867a55f3796140218fdd770e926141c9f77db57edc4545f63ba29f1fe9d

WORKDIR /srv/app

# renovate: datasource=github-tags depName=python/cpython
ENV PYTHON_VERSION=v2.7.18

RUN apk update && \
  apk upgrade && \
  apk add build-base git expat-dev openssl-dev zlib-dev ncurses-dev bzip2-dev gdbm-dev sqlite-dev libffi-dev readline-dev linux-headers && \
  curl -sLo - https://www.python.org/ftp/python/${PYTHON_VERSION#v}/Python-${PYTHON_VERSION#v}.tgz | tar -xzf - -C /tmp && \
  cd /tmp/Python-${PYTHON_VERSION#v} && \
  ./configure --prefix=/usr --enable-shared --with-threads --enable-ipv6 --with-system-ffi --with-system-expat --with-system-zlib --enable-unicode=ucs4 && \
  make && \
  make install && \
  cd && \
  rm -rf /tmp/Python-${PYTHON_VERSION#v} && \
  curl -sLo - https://bootstrap.pypa.io/pip/2.7/get-pip.py | python && \
  pip install -U pip tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
