FROM webhippie/alpine:latest-arm@sha256:e49de1ac7cf99a6e058858a97c587a7692036e797bb72891c61c9b24e0975002

WORKDIR /srv/app

# renovate: datasource=github-tags depName=python/cpython
ENV PYTHON_VERSION=v3.5.10

RUN apk update && \
  apk upgrade && \
  apk add build-base git expat-dev openssl-dev zlib-dev ncurses-dev bzip2-dev xz-dev sqlite-dev libffi-dev tcl-dev linux-headers gdbm-dev readline-dev && \
  curl -sLo - https://www.python.org/ftp/python/${PYTHON_VERSION#v}/Python-${PYTHON_VERSION#v}.tgz | tar -xzf - -C /tmp && \
  cd /tmp/Python-${PYTHON_VERSION#v} && \
  ./configure --prefix=/usr --disable-rpath --enable-ipv6 --enable-loadable-sqlite-extensions --enable-shared --with-lto --with-computed-gotos --with-dbmliborder=gdbm:ndbm --with-system-expat --with-system-ffi --with-threads && \
  make && \
  make install && \
  ln -sf /usr/bin/python3.5 /usr/bin/python && \
  ln -sf /usr/bin/pip3.5 /usr/bin/pip && \
  ln -sf /usr/bin/python3.5m-config /usr/bin/python-config && \
  ln -sf /usr/bin/pydoc3.5 /usr/bin/pydoc && \
  ln -sf /usr/bin/easy_install-3.5 /usr/bin/easy_install && \
  ln -sf /usr/bin/idle3.5 /usr/bin/idle && \
  cd && \
  rm -rf /tmp/Python-${PYTHON_VERSION#v} && \
  curl -sLo - https://bootstrap.pypa.io/pip/3.5/get-pip.py | python && \
  pip install -U pip tox && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
